import * as images from "../assets";
// export * as images from "../assets";

// hero data
export const heroData = {
  heroImg: images.heroImg,
  heroTitle: "Obaji festival",
  heroDesc:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea facilis quam vero quidem quisquam minima. Cum maiores, temporibus vitae corporis pariatur quos possimus asperiores libero. Placeat cumque architecto harum maiores?",
};

// about section
export const aboutData = {
  aboutImg: images.drums,
  aboutTitle: "About Obaji Festival",
  aboutDesc:
    "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis, amet! Illo, quis officia. Vel laudantium, ad accusamus quisquam temporibus veritatis reiciendis illum mollitia dignissimos dolores cupiditate eius fugit accusantium cumque, quae aperiam? Non necessitatibus inventore nisi! Neque libero nemo adipisci ipsam! Quia eveniet itaque debitis rem aut cumque voluptas eligendi corrupti in quidem. Doloremque ab ipsum architecto quasi doloribus esse assumenda suscipit, impedit, magnam voluptate debitis excepturi vitae accusamus maiores consequuntur sint voluptatum. Inventore, deserunt in. Architecto nostrum tempore molestiae, dicta aut, delectus odit laboriosam quaerat eius placeat commodi nisi velit saepe quod corporis debitis cumque facilis facere dolor iste similique, earum ducimus? Earum suscipit totam, itaque maxime aperiam culpa animi quidem impedit laboriosam unde sequi mollitia dolor natus quis? Labore aliquid totam sint deleniti quia, blanditiis ratione pariatur ipsum perferendis quidem fugiat, facere ex suscipit eum debitis inventore tenetur illo earum a laboriosam.",
};

// event data
export const eventData = [
  {
    id: 1,
    title: "Onitsha Creative Connect",
    theme: "E-merging Creativity",
    slogan: "...learn, network and have fun",
    date: "04-2-2024",
    time: "19:18",
    thumbnail: images.blog3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
    link: "https://myevent.com",
    speakers: [
      {
        name: "John Paul",
        position: "Speaker 1",
        photo: images.team1,
        socialMediaHandles: [
          { link: "https://facebook.com/john.paul.28", platform: "facebook" },
          { link: "https://twitter.com/john.paul.28", platform: "twitter" },
          { link: "https://instagram.com/john.paul.28", platform: "instagram" },
        ],
      },
      {
        name: "Mary Jane",
        position: "Speaker 2",
        photo: images.team2,
        socialMediaHandles: [
          { link: "https://facebook.com/mary.jane.23", platform: "facebook" },
          { link: "https://twitter.com/mary.jane.23", platform: "twitter" },
          { link: "https://instagram.com/maryjane_23", platform: "instagram" },
        ],
      },
    ],
    sponsors: [
      { logo: images.logo, name: "Obaji festival" },
      { logo: images.logo, name: "Tiger Ltd" },
      { logo: images.logo, name: "Indomie noodles" },
      { logo: images.logo, name: "Dangote group Ltd" },
      { logo: images.logo, name: "MTN Ltd" },
    ],
  },
  {
    id: 2,
    title: "Event 2",
    theme: "Event theme",
    slogan: "slogan for the event",
    date: "04-4-2024",
    time: "19:18",
    thumbnail: images.blog1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
    link: "https://myevent.com",
    speakers: [
      {
        name: "Mary Jane",
        position: "Speaker 1",
        photo: images.team2,
        socialMediaHandles: [
          { link: "https://facebook.com/mary.jane.23", platform: "facebook" },
          { link: "https://twitter.com/john.paul.28", platform: "twitter" },
          { link: "https://instagram.com/john.paul.28", platform: "instagram" },
        ],
      },
      {
        name: "John Paul",
        position: "Speaker 2",
        photo: images.team3,
        socialMediaHandles: [
          { link: "https://facebook.com/john.paul.28", platform: "facebook" },
          { link: "https://twitter.com/john.paul.28", platform: "twitter" },
          { link: "https://instagram.com/john.paul.28", platform: "instagram" },
        ],
      },
    ],
    sponsors: [
      { logo: images.logo },
      { logo: images.logo },
      { logo: images.logo },
      { logo: images.logo },
      { logo: images.logo },
    ],
  },
  {
    id: 3,
    title: "Event 3",
    date: "01-01-2026",
    time: "16:00",
    thumbnail: images.blog2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 4,
    title: "Event 4",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.blog3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 5,
    title: "Event 5",
    date: "01-01-2025",
    time: "16:00",
    thumbnail: images.event1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 6,
    title: "Event 6",
    date: "01-01-2025",
    time: "16:00",
    thumbnail: images.event2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 7,
    title: "Event 7",
    date: "12-01-2024",
    time: "16:00",
    thumbnail: images.event3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 8,
    title: "Event 8",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.heroImg,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 9,
    title: "Event 9",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.logo,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 10,
    title: "Event 10",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.drums,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 11,
    title: "Event 11",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.blog3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 12,
    title: "Event 12",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.blog2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 13,
    title: "Event 13",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.blog1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 14,
    title: "Event 14",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.event3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 15,
    title: "Event 15",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.event2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
  {
    id: 16,
    title: "Event 16",
    date: "01-01-2024",
    time: "16:00",
    thumbnail: images.event1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    venue: "Queen's Villa Park",
  },
];

// blog data
export const blogData = [
  {
    id: 1,
    title: "Blog 1",
    date: "01-01-2024",
    thumbnail: images.blog1,
    authorImg: images.team1,
    author: "James Bond",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "culture",
    photogallery: [images.blog1, images.event1, images.blog3, images.event3],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 2,
    title: "Blog 2",
    date: "01-01-2024",
    authorImg: images.team2,
    author: "James Bond",
    thumbnail: images.blog2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "food",
    photogallery: [images.blog2, images.event2, images.blog3, images.event1],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 3,
    title: "Blog 3",
    date: "01-01-2024",
    thumbnail: images.blog3,
    authorImg: images.team3,
    author: "James Bond",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "music",
    photogallery: [images.blog1, images.event1, images.blog3, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 4,
    title: "Blog 4",
    date: "01-01-2024",
    thumbnail: images.event1,
    authorImg: images.team4,
    author: "James Bond",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "dance",
    photogallery: [images.blog3, images.event1, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 5,
    title: "Blog 5",
    date: "01-01-2024",
    authorImg: images.team3,
    author: "James Bond",
    thumbnail: images.event2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "food",
    photogallery: [images.blog3, images.event1, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 6,
    title: "Blog 6",
    date: "01-01-2024",
    authorImg: images.team2,
    author: "James Bond",
    thumbnail: images.event3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "dance",
    photogallery: [images.blog2, images.event3, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 7,
    title: "Blog 7",
    date: "01-01-2024",
    authorImg: images.team4,
    author: "James Bond",
    thumbnail: images.heroImg,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "food",
    photogallery: [images.blog3, images.blog2, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 8,
    title: "Blog 8",
    date: "01-01-2024",
    authorImg: images.team1,
    author: "James Bond",
    thumbnail: images.logo,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "pageant",
    photogallery: [images.event3, images.event1, images.blog1, images.blog2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 9,
    title: "Blog 9",
    date: "01-01-2024",
    authorImg: images.team2,
    author: "James Bond",
    thumbnail: images.drums,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "culture",
    photogallery: [images.blog3, images.event1, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 10,
    title: "Blog 10",
    date: "01-01-2024",
    authorImg: images.team3,
    author: "James Bond",
    thumbnail: images.blog3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "dance",
    photogallery: [images.blog3, images.blog2, images.blog1, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 11,
    title: "Blog 11",
    date: "01-01-2024",
    authorImg: images.team4,
    author: "James Bond",
    thumbnail: images.blog2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "music",
    photogallery: [images.blog1, images.event1, images.blog2, images.event3],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 12,
    title: "Blog 12",
    date: "01-01-2024",
    authorImg: images.team1,
    author: "James Bond",
    thumbnail: images.blog1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "food",
    photogallery: [images.blog3, images.event1, images.event3, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 13,
    title: "Blog 13",
    date: "01-01-2024",
    authorImg: images.team2,
    author: "James Bond",
    thumbnail: images.event3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "culture",
    photogallery: [images.event3, images.event1, images.blog3, images.event2],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 14,
    title: "Blog 14",
    date: "01-01-2024",
    authorImg: images.team3,
    author: "James Bond",
    thumbnail: images.event2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "dance",
    photogallery: [images.blog3, images.blog2, images.blog1, images.event1],
    videos: "https://youtu.be/qb1jOTubnpA",
  },
  {
    id: 15,
    title: "Blog 15",
    date: "01-01-2024",
    authorImg: images.team4,
    author: "James Bond",
    thumbnail: images.event1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta aut praesentium quas dolores qui harum distinctio, magni nesciunt ex absimilique asperiores laboriosam rerum culpa, officia facilis sintnobis omnis.",
    category: "beauty",
    photogallery: [images.event3, images.event2, images.event1, images.blog2],
    videos: "https://youtu.be/Y48V8gNUvew?si=xmPIkGOi1jE1fXlC",
  },
];

// footer data
export const footerLinks = [
  {
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptate ab autem maiores accusantium commodi tempore adipisci ipsa deserunt harum ut corporis magni recusandae, dolorum, quisquam, nulla impedit voluptatibus consequatur. Veritatis?",
  },
  {
    contacts: [
      { contact: "+2348123456789", link: "tel:+2348123456789" },
      { contact: "contact@email.com", link: "mailto:contact@email.com" },
      {
        contact: "6 Ridge road, GRA, Onitsha, Anambra",
        link: "https://maps.google.com/?q='6 Ridge road, GRA, Onitsha, Anambra'",
      },
    ],
  },
  {
    socialLinks: [
      { link: "https://facebook.com/username", platform: "facebook" },
      { link: "https://wa.me/+2348123456789", platform: "whatsapp" },
      { link: "https://twitter.com/username", platform: "twitter" },
      { link: "https://instagram.com/username", platform: "instagram" },
      { link: "https://youtube.com/username", platform: "youtube" },
    ],
  },
];
